name: 🐛 test
description: aa
title: 🐛 <bug title>
labels: [bug]

body:
  - type: textarea
    attributes:
      label: 概要
      description: 発生したバグ内容を簡潔に記載してください！
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
